name: Dart Checks

on:
  push:
    paths:
    - '.github/workflows/dart_checks.yml'
    - '**.dart'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Dart pub root project
        run: dart pub get
        shell: bash
      - name: Run analyze
        run: flutter analyze --fatal-infos .

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Dart pub root project
        run: dart pub get
        shell: bash
      - name: Run format
        run: dart format --set-exit-if-changed .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Dart pub root project
        run: dart pub get
        shell: bash
      - name: Run Test
        run: flutter test
