name: Deploy apps

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-deploy-apps
  cancel-in-progress: true

jobs:
  play-store-release:
    name: Create Play Store Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
          working-directory: ./android
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Prepare upload key
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > app/keystore.jks
          echo "$KEY_PROPERTIES" > key.properties
        working-directory: ./android
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}
      - name: Build App bundle
        run: flutter build appbundle --release --build-number ${{ github.run_number }}
      - name: Fastlane upload
        run: bundle exec fastlane deploy_internal
        working-directory: ./android
        env:
          PLAY_CREDS_JSON: ${{ secrets.PLAY_CREDS_JSON }}
